- label: papers
  title: "Papers and Projects"
  date: 2025-11-02
  description: "Publications on mechanistic interpretability and AI Safety."
  math: false
  tags: ["research", "papers"]

- label: hiking
  title: "Hiking Photos"
  date: 2025-11-02
  description: "A collection of photos from various hiking adventures."
  math: false
  tags: ["photos", "hiking"]
